app:
  allowed-cross-orign: http://localhost:8080,http://10.237.202.137:8080,http://192.168.1.100:8080,http://cris15.top:8080,http://localhost:8084,http://cris15.top:8084,http://cris15.top:8084,      #可跨域资源，以逗号分隔

spring:
  profiles:
    active: dev
